services:

 mongo:
  image: mongo
  restart: always
  volumes:
   - mongodb_data:/data/db
  ports:
   - "27017:27017"
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: root
   MONGODB_USER: mongouser
   MONGODB_DATABASE: mongodb
   MONGODB_PASS: mongopwd

 mongo-express:
  image: mongo-express
  restart: always
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
   ME_CONFIG_MONGODB_ADMINPASSWORD: admin
   ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

volumes:
  mongodb_data: